export const seedPrompts = [
  { text: "What's one thing on your mind right now?", pillarId: null },
  { text: "What would make today a good day?", pillarId: null },
  { text: "What's something you noticed recently?", pillarId: null },
  { text: "What are you looking forward to?", pillarId: null },
  { text: "What's one thing you'd tell yourself a year from now?", pillarId: null },
  { text: "What's taking up most of your mental energy today?", pillarId: null },
  { text: "What's something small that made you smile?", pillarId: null },
  { text: "What would you like to remember about today?", pillarId: null },
  { text: "If today had a theme, what would it be?", pillarId: null },
  { text: "What's one thing you're proud of right now?", pillarId: null },
  { text: "How does your body feel today?", pillarId: null },
  { text: "What's one thing you did for yourself today?", pillarId: null },
  { text: "How did you move your body today?", pillarId: null },
  { text: "What's one healthy choice you made today?", pillarId: null },
  { text: "How's your energy level right now?", pillarId: null },
  { text: "What's one thing you moved forward today?", pillarId: null },
  { text: "What problem are you trying to solve right now?", pillarId: null },
  { text: "What's a skill you're building?", pillarId: null },
  { text: "What's the most interesting part of your work right now?", pillarId: null },
  { text: "What would you do differently at work tomorrow?", pillarId: null },
  { text: "Who made an impact on you recently?", pillarId: null },
  { text: "What's one thing you're grateful for about someone in your life?", pillarId: null },
  { text: "Who have you been thinking about lately?", pillarId: null },
  { text: "What's a conversation you'd like to have?", pillarId: null },
  { text: "How did you connect with someone today?", pillarId: null },
  { text: "What's inspiring you right now?", pillarId: null },
  { text: "What would you create if you had no constraints?", pillarId: null },
  { text: "What's a creative idea you've been sitting on?", pillarId: null },
  { text: "What did you make or build recently?", pillarId: null },
  { text: "What's one financial decision you're weighing?", pillarId: null },
  { text: "What does financial peace of mind look like for you?", pillarId: null },
  { text: "What's one money habit you're working on?", pillarId: null },
  { text: "What are you grateful for today?", pillarId: null },
  { text: "What emotion is most present right now?", pillarId: null },
  { text: "What's one thing you can let go of today?", pillarId: null },
  { text: "Where do you feel most at peace?", pillarId: null },
  { text: "What's something you accepted today?", pillarId: null },
  { text: "What's something you learned recently?", pillarId: null },
  { text: "What's a question you've been sitting with?", pillarId: null },
  { text: "What's something you'd like to understand better?", pillarId: null },
  { text: "What changed your perspective recently?", pillarId: null },
  { text: "What book, article, or idea has stuck with you?", pillarId: null },
];
